name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint using ESLint and Prettier

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          show-progress: false

      - name: Use LTS Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install packages
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 22
          - 24
          - 26
          - latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install npm latest for Node.js latest
        if: matrix.node-version == 'latest'
        run: npm install -g npm@latest

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run tap
